feat: add nodejs generator (#91)
Signed-off-by: Michael Beemer <michael.beemer@dynatrace.com>

diff --git a/.github/workflows/pr-test.yml b/.github/workflows/pr-test.yml
--- a/.github/workflows/pr-test.yml
+++ b/.github/workflows/pr-test.yml
@@ -31,6 +31,7 @@ jobs:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
+          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || '' }}
       - uses: actions/setup-go@v5
         with:
           go-version-file: 'go.mod'
@@ -38,4 +39,8 @@ jobs:
       - run: make generate-docs
       - name: Check no diff
         run: |
-          if [ ! -z "$(git status --porcelain)" ]; then echo "::error file=Makefile::Doc generation produced diff. Run 'make generate-docs' and commit results."; exit 1; fi
+          if [ ! -z "$(git status --porcelain)" ]; then
+            echo "::error file=Makefile::Doc generation produced diff. Run 'make generate-docs' and commit results."
+            git diff
+            exit 1
+          fi
