testing error message, remove additional cache
Signed-off-by: Michael Beemer <beeme1mr@users.noreply.github.com>

diff --git a/.github/workflows/pr-test.yml b/.github/workflows/pr-test.yml
--- a/.github/workflows/pr-test.yml
+++ b/.github/workflows/pr-test.yml
@@ -20,15 +20,6 @@ jobs:
       - uses: actions/setup-go@v5
         with:
           go-version-file: 'go.mod'
-      - name: Module cache
-        uses: actions/cache@v4
-        with:
-          path: |
-            ~/.cache/go-build
-            ~/go/pkg/mod
-          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
-          restore-keys: |
-            ${{ runner.os }}-go-
 
       - name: Run tests
         run: go test ./...
@@ -43,17 +34,8 @@ jobs:
       - uses: actions/setup-go@v5
         with:
           go-version-file: 'go.mod'
-      - name: Module cache
-        uses: actions/cache@v4
-        with:
-          path: |
-            ~/.cache/go-build
-            ~/go/pkg/mod
-          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
-          restore-keys: |
-            ${{ runner.os }}-go-
 
       - run: make generate-docs
       - name: Check no diff
         run: |
-          if [ ! -z "$(git status --porcelain)" ]; then echo "::error::Doc generation produced diff. Run 'make generate-docs' and commit results."; exit 1; fi
+          if [ ! -z "$(git status --porcelain)" ]; then echo "::error file=Makefile,line=8::Doc generation produced diff. Run 'make generate-docs' and commit results."; exit 1; fi
