improve doc diff output
Signed-off-by: Michael Beemer <beeme1mr@users.noreply.github.com>

diff --git a/.github/workflows/pr-test.yml b/.github/workflows/pr-test.yml
--- a/.github/workflows/pr-test.yml
+++ b/.github/workflows/pr-test.yml
@@ -38,4 +38,8 @@ jobs:
       - run: make generate-docs
       - name: Check no diff
         run: |
-          if [ ! -z "$(git status --porcelain)" ]; then echo "::error file=Makefile::Doc generation produced diff. Run 'make generate-docs' and commit results."; exit 1; fi
+          if [ ! -z "$(git status --porcelain)" ]; then
+            echo "::error file=Makefile::Doc generation produced diff. Run 'make generate-docs' and commit results."
+            git diff
+            exit 1
+          fi
